language: ruby
rvm:
  - 1.9.3
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - ruby-head

gemfile:
  - gemfiles/Gemfile.rails-3.0
  - gemfiles/Gemfile.rails-4.0
  - gemfiles/Gemfile.rails-5.0

matrix:
  exclude:
  - rvm: 1.9.3
    gemfile: gemfiles/Gemfile.rails-5.0
  - rvm: 2.0
    gemfile: gemfiles/Gemfile.rails-5.0
  - rvm: 2.1
    gemfile: gemfiles/Gemfile.rails-5.0

script: bundle exec rake test
